// BUG FIX: the crate `onnx = "0.2"` does not exist on crates.io.
// The correct approach for parsing ONNX models in Rust is to use the
// `tract-onnx` crate (pure-Rust, widely used for edge/embedded deployments).
// Weight extraction is done via tract typed IR instead of raw NodeProto.

use std::fs::File;
use std::io::Write;
use anyhow::{Context, Result};

/// Compile an ONNX model to a synthesisable Verilog weights file.
///
/// Extracts all initialiser tensors, quantises them to INT8, and emits a
/// Verilog `reg` array per tensor so the RTL weight-SRAM can be initialised
/// at synthesis time.
pub fn compile_onnx_to_verilog(onnx_path: &str, verilog_path: &str) -> Result<()> {
    use tract_onnx::prelude::*;

    // BUG FIX: the original called `onnx::load_model()` which does not exist.
    let model = tract_onnx::onnx()
        .model_for_path(onnx_path)
        .with_context(|| format!("Failed to open ONNX model: {}", onnx_path))?
        .into_optimized()
        .with_context(|| "Failed to optimise ONNX model")?;

    // Collect constant (weight/bias) tensors from the graph.
    let mut weight_tensors: Vec<(String, Vec<f32>)> = Vec::new();
    for node in model.nodes() {
        if let Some(fact) = node.op_as::<tract_core::ops::konst::Const>() {
            let tensor = fact.0.clone().into_tensor();
            if tensor.datum_type() == DatumType::F32 {
                let data: Vec<f32> = tensor.as_slice::<f32>().unwrap_or(&[]).to_vec();
                if !data.is_empty() {
                    weight_tensors.push((node.name.clone(), data));
                }
            }
        }
    }

    if weight_tensors.is_empty() {
        anyhow::bail!(
            "No float32 weight tensors found in {}. \
             Ensure the model contains Constant/initialiser nodes.",
            onnx_path
        );
    }

    let mut v = File::create(verilog_path)
        .with_context(|| format!("Cannot create output file: {}", verilog_path))?;

    writeln!(v, "// Auto-generated by Hyze IPU Rust Compiler")?;
    writeln!(v, "// Source: {}", onnx_path)?;
    writeln!(v, "")?;

    for (name, weights) in &weight_tensors {
        // Sanitise name to a valid Verilog identifier.
        let safe_name: String = name
            .chars()
            .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
            .collect();

        let quantised = quantize_int8(weights);

        // BUG FIX: original used `(weights1.len() - 1)` which panics on empty
        // vectors in debug mode.  Using saturating_sub(1) is always safe.
        writeln!(
            v,
            "reg [7:0] {} [0:{}];",
            safe_name,
            quantised.len().saturating_sub(1)
        )?;
        writeln!(v, "initial begin")?;
        for (i, &byte) in quantised.iter().enumerate() {
            writeln!(v, "  {}[{}] = 8'h{:02x};", safe_name, i, byte)?;
        }
        writeln!(v, "end")?;
        writeln!(v, "")?;
    }

    println!(
        "Compiled {} -> {} ({} weight tensor(s))",
        onnx_path,
        verilog_path,
        weight_tensors.len()
    );
    Ok(())
}

/// Quantise f32 weights to INT8 stored as u8 with a +128 unsigned bias.
///
/// BUG FIX: the original divided 127.0 by the *sum* of absolute values
/// instead of the *maximum*, producing wrong scales for large tensors and
/// NaN when the sum is zero.  Correct per-tensor symmetric INT8 uses max.
fn quantize_int8(f32_weights: &[f32]) -> Vec<u8> {
    let max_abs = f32_weights
        .iter()
        .map(|&x| x.abs())
        .fold(0.0f32, f32::max);

    // Avoid division by zero for all-zero weight tensors.
    let scale = if max_abs > 0.0 { 127.0 / max_abs } else { 1.0 };

    f32_weights
        .iter()
        .map(|&x| ((x * scale).clamp(-128.0, 127.0) as i8 as i16 + 128) as u8)
        .collect()
}
